### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by ghost** [wlbirula/TTS4Anki#1]
Hey! Hope you're doing fine :) I'm getting this error on Manjaro when launching:

```
Traceback (most recent call last):
  File "/home/yaoberh/TTS4Anki/tts4anki.py", line 85, in <module>
    app = gui("Text-To-Speech for ANKI v. " + version, useTtk=True)
  File "/home/yaoberh/.local/lib/python3.10/site-packages/appJar/appjar.py", line 582, in __init__
    self.topLevel = tkinter()
TypeError: 'module' object is not callable

```

**Comment by ghost** [comment]
Seems this is an appjar problem on my side. Upgraded through pip and now it works!
